[build]
  base = "driver-interface"
  command = "CI= npm run build"
  publish = "build"

[build.environment]
  CI = ""
  NODE_VERSION = "16"
  REACT_APP_GOOGLE_MAPS_API_KEY = "AIzaSyDTz32YKciffswwF5GlXrnVfG9aa9hZNWE"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
