[build]
  base = "driver-interface"
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_GOOGLE_MAPS_API_KEY = "AIzaSyDTz32YKciffswwF5GlXrnVfG9aa9hZNWE"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
