[build]
  base = "driver-interface"
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_GOOGLE_MAPS_API_KEY = "AIzaSyDTz32YKciffswwF5GlXrnVfG9aa9hZNWE"
